TareaRickMorty/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.RickMortyAPP.urls', namespace='rickmortyapp')),
]

apps/RickMortyAPP/urls.py
from django.conf.urls import url
from django.urls import include, path
from .views import episode, character, index, location, searchs
from apps.RickMortyAPP.views import episode, character, index, location, searchs

app_name = 'rickmortyapp'

urlpatterns = [
    path('', index, name ='index'),
    path('episode/<int:id>', episode, name='episode'),
    path('character/<int:id>', character, name='character'),
    path('location/<int:id>', location, name='location'),
    path('searchs/', searchs, name='searchs')
]

apps/RickMortyAPP/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/RickMortyAPP/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
import json
import requests


URL = 'https://integracion-rick-morty-api.herokuapp.com/api/'
# Create your views here.
def index(request):
    url = URL + '/episode/'
    req = requests.get(url).json()
    context = {}
    context['results'] = req['results']
    while req['info']['next'] != '':
        req = requests.get(req['info']['next']).json()
        context['results'].extend(req['results'])
    return render(request, 'index.html', context)

def episode(request,id):
    url = URL + '/episode/' + str(id)
    context = requests.get(url).json()
    characters = context['characters']
    characters_ids = []
    characters_info = []
    for i in characters:
        characters_ids.append(int(i.split('/')[-1]))
    url2 = URL + '/character/' + str(characters_ids)
    req = requests.get(url2).json()
    for i in req:
        characters_info.append([i['name'], i['id'], i['image']])
    context['characters_info'] = characters_info
    print(context)
    return render(request, 'episode.html', context)


def character(request, id):
    url = URL + '/character/' + str(id)
    context = requests.get(url).json()
    episodes_ids = []
    episodes_names = []
    for i in context['episode']:
        episodes_ids.append(int(i.split('/')[-1]))
    url2 = URL + '/episode/' + str(episodes_ids)
    req = requests.get(url2).json()
    for i in req:
        episodes_names.append([i['name'], i['id']])
    origin_name = context['origin']['name']
    origin_id = context['origin']['url'].split('/')[-1]
    location_name = context['location']['name']
    location_id = context['location']['url'].split('/')[-1]
    context['episode_info'] = episodes_names
    context['origin_name'] = origin_name
    context['origin_id'] = origin_id
    context['location_name'] = location_name
    context['location_id'] = location_id
    print(context)
    return render(request, 'characters.html', context)

def location(request, id):
    url= URL + '/location/' + str(id)
    context = requests.get(url).json()
    characters_ids = []
    for i in context['residents']:
        characters_ids.append(int(i.split('/')[-1]))
    url2 = URL + '/character/' + str(characters_ids)
    req = requests.get(url2).json()
    characters_info = []
    for i in req:
        characters_info.append([i['id'], i['name'], i['image']])
    context['characters_info'] = characters_info
    print(context)
    return render(request, 'location.html', context)
    
def searchs(request):
    context = {}
    name = request.GET['nombre']
    urlCharacter = URL + '/character/?name=' + name
    urlLocation = URL + '/location/?name=' + name
    urlEpisode = URL + '/episode/?name=' + name
    req = requests.get(urlCharacter).json()
    print('error' in req.keys())
    if not 'error' in req.keys():
        context = {'results_character': req['results']}
        while req['info']['next'] != '':
            req = requests.get(req['info']['next']).json()
            context['results_character'].extend(req['results'])
    else:
        context = {'results_character': None}
    req = requests.get(urlLocation).json()
    if not 'error' in req.keys():
        context['results_location'] = req['results']
        while req['info']['next'] != '':
            req = requests.get(req['info']['next']).json()
            context['results_location'].extend(req['results'])
            print('\n')
        print(context['results_location'])
        print('\n')
    else:
        context['results_location'] = None
    req = requests.get(urlEpisode).json()
    print(req)
    if not 'error' in req.keys():
        context['results_episode'] = req['results']
        while req['info']['next'] != '':
            req = requests.get(req['info']['next']).json()
            context['results_episode'].extend(req['results'])
    else:
        context['results_episode'] = None
    return render(request,  'searchs.html', context)
    

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang= "es">
<head>
    <meta charset="utf-8">
    {% block static %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
{% block navbar %}
<div class="Navbar">
    <a href="{% url 'rickmortyapp:index' %}">
        <img src='../../static/images/toppng.com-rick-and-morty-portal-282x379.png' style="width: 30px; height: 30px;" href="{% url 'rickmortyapp:index' %}">
    </a>
    <form action="{% url 'rickmortyapp:searchs' %}">
        <input type="text" placeholder="Wuba luba dub dub" name="nombre">
        <button type="submit" class="search_btn" >GO</button>
    </form>
</div>
{% endblock %}

<body class="BaseContainer">
<div>

    {% block content %}
    {% endblock %}
    
    {% block footer %}
    {% endblock %}
</div>
</body>
</html>

templates/characters.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container2">
    <div style="flex-direction: row; display: flex; padding-top: 15px;">
        <img src="{{image}}" style="border-radius: 50%; max-height: 300px; max-width: 300px; padding-left: 25px; padding-top: 25px;">
        <div style="padding-left: 50px; padding-top: 25px;">
            <h1> {{name}} </h1>
            <div style="flex-direction: row; display: flex;"> 
                {% if origin_name == 'unknown' %}
                <h1>Unknown origin place</h1>
                {% else %}
                <h2>Origin place:</h2>
                <h2 style="padding-left: 25px;"><a href="{% url 'rickmortyapp:location' id=origin_id %}">{{origin_name}}</a></h2>
                {% endif %}
            </div>
            <div style="flex-direction: row; display: flex;"> 
                {% if location_name == 'unknown' %}
                <h1>unknown actual location</h1>
                {% else %}
                <h2>Actual location:</h2>
                <h2 style="padding-left: 25px;"><a href="{% url 'rickmortyapp:location' id=location_id %}">{{location_name}}</a></h2>
                {% endif %}
            </div>
            <div style="flex-direction: row; display: flex;">
                <h3>Status: {{status}} </h3>
                <div style="flex-direction: column; display: flex; padding-left: 25px;">
                    <h3>Species: {{species}} </h3>
                    {% if type != '' %}
                    <h3>Type: {{type}} </h3>
                    {% endif %}
                </div>
                <h4 style="padding-left: 25px;">Gender: {{gender}}</h4>
            </div>
        </div>
    </div>
    <div style="display: flex; flex-direction: column; padding-top: 25px; padding-left: 100px;">
        <div>
            <h2>Episodes of appearence:</h2>
        </div>
        <div style="padding-left: 100px;">
            {% for i, j in episode_info %}
            <h3 id="title"><a href="{% url 'rickmortyapp:episode' id=j %}">{{i}}</a></h3>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/episode.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container2">
    <div style="display: flex; flex-direction: indent-block;">
        <h1 id="title">{{name}}</h1>
        <div>
            <h2 id="sub-title">Episode: {{episode}}</h2> 
            <h2 id="sub-title">Release: {{air_date}}</h2> 
        </div>
    </div>
    <div>
        <h1 id="sub-title">Characters:</h1>
    </div>
    {% for i, j, k in characters_info %}
    <div class="listing">
        <img src="{{k}}" style="border-radius: 50%; max-width: 100px; max-height: 100px;"> 
        <h2><a href="{% url 'rickmortyapp:character' id=j %}" > {{i}}  </a> </h2>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/index.html
{% extends 'base/base.html' %}
{% block content %}
<div style="flex-direction: row; display: flex; align-items: baseline;">
    <img style="padding-left: 30%; padding-top: 45px;" src='../static/images/R&M_no_background.png'>
    <h6 style="color:blanchedalmond; font-family: 'get_schwiftyregular'; font-size: 25px;">
        <a href="https://github.com/Felipehanckes/TareasTallerIntegracion"> byFeHa 
        </a> 
    </h6>
</div>
<div class="container">
    <div>
    </div>
    <div class="listing">
        <div style="display: flex; flex-direction: row; margin-left: 100px;">
            <h3 id="head">Chapter name</h3>
            <h3 id="head">Release date</h3>
        </div> 
    </div>
    {% if results %}
    {% for episode in results %}
    <div class="listing">
        <h3>{{episode.episode}}</h3>
        <h3 id="body"><a href="{% url 'rickmortyapp:episode' id=episode.id %}">{{episode.name}}</a></h3>
        <h3 id="body">{{episode.air_date}}</h3>
    </div>
    {% endfor %}
    {% else %}
    <h1> No hay resultados, la API debio fallar</h1>
    {% endif %}
</div>
{% endblock %}

templates/location.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container2">
    <div style="display: flex; flex-direction: indent-block;">
        <h1 id="title2">{{name}}</h1>
        <div>
            <h2 id="sub-title2">Type: {{type}}</h2> 
            <h2 id="sub-title2">Dimension: {{dimension}}</h2> 
        </div>
    </div>
    <h1 id="sub-title">Residents: </h2>
    {% for iid, iname, image in characters_info %}
    <div class="listing">    
        <div style="display: flex; flex-direction: row;">
            <img src="{{image}}" style="border-radius: 50%; max-width: 100px; max-height: 100px;"> 
            <h2><a href="{% url 'rickmortyapp:character' id=iid %}"> {{iname}}</a></h2>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}

templates/searchs.html
{% extends 'base/base.html' %}
{%block content %}
<div style="flex-direction: row; display: flex;">
    <a href="{% url 'rickmortyapp:index' %}" style="padding-left: 30%; padding-top: 45px;">
        <img  src='../static/images/R&M_no_background.png'>
    </a>
</div>
<div class='container'>

    {% if results_character != None %}
    <h1 id='title'>Character search results</h1>
    {% for character in results_character %}
    <div class="listing">
        <div style="display: flex; flex-direction: row; align-items: center;">
            <img src="{{character.image}}" style="border-radius: 50%; max-width: 100px; max-height: 100px;"> 
            <h1><a href="{% url 'rickmortyapp:character' id=character.id %}">{{character.name}} </a></h1>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    
    {% if results_location != None %}
    <h1 id='title'>Location search results</h1>
    {% for location in results_location %}
    <div class="listing">
        <h1><a href="{% url 'rickmortyapp:location' id=location.id %}">{{location.name}} </a></h1>
    </div>
    {% endfor %}
    {% endif %}

    
    
    {% if results_episode != None %}
    <h1 id='title'>Episode search results</h1>
    {% for episode in results_episode %}
    <div class="listing">
        <h1><a href="{% url 'rickmortyapp:episode' id=episode.id %}">{{episode.name}} </a></h1>
    </div>
    {% endfor %}
    {% endif %}

    {% if results_character == None %}
    <h1 id='title'>No Character results</h1>
    {% endif %}
    {% if results_location == None %}
    <h1 id='title'>No Location results</h1>
    {% endif %}
    {% if results_episode == None %}
    <h1 id='title'>No Episode results</h1>
    {% endif %}
</div>

{% endblock %}